#!/usr/bin/env bash

rm -rf dist
mkdir -p dist
echo "build src/ctrlz.ls -> dist/ctrlz.js ..."
npx lsc -cp src/ctrlz.ls > dist/ctrlz.js
echo "minifying ctrlz.js ..."
npx uglifyjs dist/ctrlz.js > dist/ctrlz.min.js


echo "merge ctrlz and module into ctrlz.bundle.js..."
cat node_modules/@plotdb/json0/dist/json0.min.js dist/ctrlz.min.js > dist/ctrlz.bundle.min.js

echo "deploy into local web ..."
rm -rf web/static/assets/lib/ctrlz/dev/
mkdir -p web/static/assets/lib/ctrlz/dev/
cp -R dist/* web/static/assets/lib/ctrlz/dev/
echo "done."

